### PR TITLE
Ignore comments in equation environment

### LINKED ISSUE #60: Comments in the equeations
I don't know well but he say so. I should check it later.
https://twitter.com/coriandered/status/1350066641451642882?s=20

If not, I close this issue.

### PR DESCRIPTION
**Pull request by pddg**
fix #60 

## Fix

- Do not insert a comment if the parent node is `CodeBlock` or `Code`.

### CODE REVIEW

**Comment by pddg** [comment]
Some breaking changes are introduced in latex-utensils v3.0.0.
https://github.com/tamuratak/latex-utensils/blob/73bf65e681edafd16fc4aa0ba50e7fa9eba2fe25/CHANGELOG.md#300-2021-01-01

Bump up version after supporting `UrlCommand`, `HrefCommand` and `LabelCommand`.

**Comment by tani** [comment]
> Some breaking changes are introduced in latex-utensils v3.0.0.
> [tamuratak/latex-utensils@`73bf65e`/CHANGELOG.md#300-2021-01-01](https://github.com/tamuratak/latex-utensils/blob/73bf65e681edafd16fc4aa0ba50e7fa9eba2fe25/CHANGELOG.md#300-2021-01-01)
> 
> Bump up version after supporting `UrlCommand`, `HrefCommand` and `LabelCommand`.

What does this plugin return if the node is labeled these label?

**Comment by pddg** [comment]
`UrlCommand` and `HrefCommand` will be interpreted as `Link` node.
https://textlint.github.io/astexplorer/

`LabelCommand` is difficult......
I think it should be a `Code` node.

**Comment by tani** [comment]
> `LabelCommand` is difficult......
> I think it should be a `Code` node.

How about `Html` node because it is metadata of the document like comments.

**Comment by pddg** [comment]
You're absolutely right. I think I'll go that direction. However, I would like to introduce them in a different PR.

**Comment by tani** [comment]
Thank you. We finally ready to merge this change!
Before merging, I have one more question.

Don't we use `enableMathCharacterLocation` option?

**Comment by pddg** [comment]
Since both `inlineMath` and `equation` environment are parsed as `CodeBlock`, it seems that the location information of `math.character` is not necessary.

**Comment by tani** [comment]
I see. thanks.

**Pull request merged**
