### PR TITLE
Release v1.2.0

### PR DESCRIPTION
**Pull request by pddg**
I think it's time to release.

### CODE REVIEW

**Comment by pddg** [comment]
I was not sure which version change of the supported runtime was considered a major, minor, or patch version change.

**Review by kn1cht — APPROVED** [review]

**Comment by pddg** [comment]
@tani 
Publishing to npm is failed due to `npm ERR! 404 Not Found - PUT https://registry.npmjs.org/textlint-plugin-latex2e - Not found`.
https://github.com/textlint/textlint-plugin-latex2e/runs/6254545854?check_suite_focus=true#step:7:72

Do you see what is happening?

**Comment by tani** [comment]
@pddg The access token was expired. I have updated it just now. Could you make new a release again? Cheers.

**Comment by pddg** [comment]
@tani 
I just re-run the workflow and it succeeds!
https://github.com/textlint/textlint-plugin-latex2e/actions/runs/2256922469

**Comment by tani** [comment]
Great! Thanks 🎉

**Pull request merged**
