### PR TITLE
Offline test

### LINKED ISSUE #39: Run test in offline environment
textlint-rule-ginger uses Ginger API provided by Ginger.
We need to run tests with the internet connect because the rule calls API with HTTP protocol.
We should replace tests with other rules such as textlint-rule-spelling.

### PR DESCRIPTION
**Pull request by tani**
Closes #39.
Yes, we should use PR to commit master branch.
Thanks for giving advices @pddg :+1:

### CODE REVIEW

**Review by pddg — CHANGES_REQUESTED** [review]
textlint-rule-spellchecker seems not to be maintained.
And since we don't want to spell or grammar check, we don't need to choose this instead of textlint-rule-ginger, do we?

I think it is easier to write tests using rules that are more predictable in their results. For example:

- textlint-rule-en-capitalization
- textlint-rule-sententh-length
- textlint-rule-no-todo
- ...etc

**Comment by tani** [comment]
Excuse me, you mean textlint-rule-spelling? I know textlint-rule-spellchecker is obsoleted. textlint-rule-spelling is developed by me and released latest verssion at the 3 month ago. I can keep the maintain the plugin and rule as possible.

> I think it is easier to write tests using rules that are more predictable in their results. For example:

I'd like to test **fixable** rule, which means that the rule should support `textlint --fix` function.
They are not fixable rule, which shows only errors. Thus, I uses spellchecking rules.

**Comment by pddg** [comment]
Wow, It was a mistake on my part. Sorry.

**Review by pddg — APPROVED** [review]
LGTM

**Comment by tani** [comment]
Thanks for reviewing!

**Pull request merged**
