### PR TITLE
Add tex2tast command

### PR DESCRIPTION
**Pull request by pddg**
## Changes

- Add `commander` module as optional dependency.
- Add `tex2tast` command.
  - It named from "TeX to textlint AST".

This command is a development utility. We can confirm the output of our plugin easily.

```bash
# Link current package if you want to tex2tast inside textlint-plugin-latex2e project.
$ npm link
$ npx tex2tast   
Usage: tex2tast [OPTIONS] FILE

Options:
  -l, --location  enable location and range
  -r, --raw       include raw
  -h, --help      display help for command
```

A sample source is as follows.

```tex
\section{title}

sentence
```

```bash
$ npx tex2tast sample.tex 
{
  "type": "Document",
  "children": [
    {
      "depth": 2,
      "type": "Header",
      "children": [
        {
          "type": "Str",
          "value": "title"
        }
      ]
    },
    {
      "type": "Html",
      "value": "\n\n"
    },
    {
      "type": "Paragraph",
      "children": [
        {
          "type": "Str",
          "value": "sentence"
        }
      ]
    }
  ]
}
```

## NOTE

Current `lockfileVersion` in `package-lock.json` is 2. This change was introduced in 48cfeaa553afd15f879d1ca2aec204afe927440e .

@tani 
Maybe, is the version of your `npm` command v7.x? npm@v7 uses `lockfileVersion: 2`.
https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major.html

We can use either v6 or v7, but we want to have an agreement on which one to use. 
I think that we should use v6 since the `npm` command installed on CI is v6 now.
https://github.com/textlint/textlint-plugin-latex2e/runs/1939827921?check_suite_focus=true#step:3:7
https://github.com/textlint/textlint-plugin-latex2e/runs/1939827904?check_suite_focus=true#step:3:8

### CODE REVIEW

**Comment by tani** [comment]
This is the nice what I want! Yes you're right, I updated npm in the local environment. As you said, we should follow to the test environment.

**Review by tani — CHANGES_REQUESTED** [review]
Could you write `bin/tex2tast` in TypeScript?

1. Create `src/tex2tast.ts`
2. Add `postbuild` hook to move the artifact to `bin/tex2tast`

**Comment by tani** [comment]
After the upload to npm, we can use `npx -p textlint-plugin-latex2e tex2tast <file>`

**Comment by pddg** [comment]
I've tried, but I'm not sure if I'm doing it right.

**Review by tani — APPROVED** [review]

**Comment by tani** [comment]
Thank you for your effort.

**Pull request merged**
