### PR TITLE
GPLv3 to MIT

### LINKED ISSUE #75: RFC: Relicesing to MIT
When we make online textlint playground with this plugin,
GPLv3 license possibly courses problem. I propose to change the license from GPLv3 to MIT.
If you agree with me, comment this thread please because I need to get agreement by **all** contributors.

Contributors, @w0xel @pddg @kn1cht 
Thank you for your contributions!

### PR DESCRIPTION
**Pull request by tani**
Closes #75.

I think we have to add the CLA bot.

### CODE REVIEW

**Review by pddg — APPROVED** [review]
LGTM

**Comment by pddg** [comment]
@tani Please squash the commits into one commit in this PR.

**Comment by tani** [comment]
@pddg Okay, I will do it.

**Comment by tani** [comment]
As this repository is protected, we could not overwrite history when we merge it once. So, next time I follow it.

**Pull request merged**
