### PR TITLE
Update dependabot.yml

### PR DESCRIPTION
**Pull request by tani**
I want to add the feature automatically merging dependency versioned a minor update.

### CODE REVIEW

**Comment by pddg** [comment]
@tani 
As for the production dependency, why don't we make the patch version only auto-merge, since it will be auto-merged without noticing the new features of latex-utensils?

**Comment by tani** [comment]
I see, the minor version update of latex-utensils means adding a few new node types.
I will update it. Thanks.

**Comment by tani** [comment]
I got bad news. https://stackoverflow.com/questions/64116781/how-do-i-automerge-dependabot-updates-config-version-2
We cannot make auto-merging facilities with this.

**Comment by pddg** [comment]
Oh, my God……From the discussion, it may be doubtful that `automerge` of GitHub-native dependabot will be enabled in the future.
We have three options:

1. Use Renovate instead.
  - Renovate has auto-merge feature.
2. Make the update frequency once a month instead.
  - This will reduce our efforts. Once a week was too much for us.
3. Do nothing.

I thought 1 or 2 would be better. What do you think?

**Comment by tani** [comment]
First, I consider continuing to use dependabot with https://github.com/fastify/github-action-merge-dependabot but it looks hard to deploy because of [this post](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/). I have no experience to use Renovate. It, however, is attractive. Could you do it?

**Comment by pddg** [comment]
I tried to install Renovate (GitHub App) to this repo, however, it does not appear in the `integrations` page of the settings page of this repo.
Why......
I also try to install renovate-approve (This is required to merge PRs automatically. It will approve PRs from Renovate), and it succeeded.

**Comment by pddg** [comment]
I'm not sure, but it seems to have worked.
https://github.com/textlint/textlint-plugin-latex2e/pull/129

**Comment by tani** [comment]
Thanks. I also cannot see it at `integrations, but it looks working well.
There is no problem because we cannot see them even if dependabot.

**Comment by tani** [comment]
Closed by #129

**Pull request closed without merging**
