### PR TITLE
Do not build test files

### LINKED ISSUE #140: v1.1.2 seems not to work
## Environment

- Ubuntu 20.04.2 LTS
- Node v14.16.1
- textlint-plugin-latex2e v1.1.2
- textlint v11.9.0
- textlint-rule-sentence-length v2.2.0

## How to reproduce

```bash
$ mkdir latex2e-not-work && cd latex2e-not-work
$ npm init -y && npm install --save \
    textlint@11.9.0 \
    textlint-rule-sentence-length@2.2.0 \
    textlint-plugin-latex2e@1.1.2
$ cat << EOF > sample.tex
\begin{document}
sample source
\end{document}
EOF
$ cat << EOF > .textlintrc
{
    "plugins": ["latex2e"],
    "rules": {"sentence-length": true}
}
EOF
$ npx textlint sample.tex
```

## Expected behavior

It works well and no problems are detected.

## Actual behavior

textlint says `"Failed to load textlint's plugin module: "latex2e" is not found."`.

```bash
$ npx textlint sample.tex
✖ Error
Failed to load textlint's plugin module: "latex2e" is not found.
See FAQ: https://github.com/textlint/textlint/blob/master/docs/faq/failed-to-load-textlints-module.md


✖ Stack trace
ReferenceError: Failed to load textlint's plugin module: "latex2e" is not found.
See FAQ: https://github.com/textlint/textlint/blob/master/docs/faq/failed-to-load-textlints-module.md

    at TextLintModuleResolver.resolvePluginPackageName (/home/pudding/Factory/latex2e-not-work/node_modules/textlint/lib/engine/textlint-module-resolver.js:95:19)
    at TextLintModuleLoader.loadPlugin (/home/pudding/Factory/latex2e-not-work/node_modules/textlint/lib/engine/textlint-module-loader.js:101:43)
    at /home/pudding/Factory/latex2e-not-work/node_modules/textlint/lib/engine/textlint-module-loader.js:91:23
    at Array.forEach (<anonymous>)
    at TextLintModuleLoader.loadFromConfig (/home/pudding/Factory/latex2e-not-work/node_modules/textlint/lib/engine/textlint-module-loader.js:90:28)
    at TextLintEngine.AbstractTextLintEngine (/home/pudding/Factory/latex2e-not-work/node_modules/textlint/lib/engine/textlint-engine-core.js:98:27)
    at new TextLintEngine (/home/pudding/Factory/latex2e-not-work/node_modules/textlint/lib/textlint-engine.js:26:47)
    at Object.executeWithOptions (/home/pudding/Factory/latex2e-not-work/node_modules/textlint/lib/cli.js:203:26)
    at Object.execute (/home/pudding/Factory/latex2e-not-work/node_modules/textlint/lib/cli.js:104:25)
    at /home/pudding/Factory/latex2e-not-work/node_modules/textlint/bin/textlint.js:37:20
```

textlint-plugin-latex2e is installed successfully.

```bash
$ ll -d node_modules/textlint-plugin-latex2e/
drwxr-xr-x 6 pudding pudding 4096 May  8 11:06 node_modules/textlint-plugin-latex2e/
```

textlint-plugin-latex2e@1.1.0 works well.

```
$ npm install --save textlint-plugin-latex2e@v1.1.0
npm WARN latex2e-not-work@1.0.0 No description
npm WARN latex2e-not-work@1.0.0 No repository field.

+ textlint-plugin-latex2e@1.1.0
removed 1 package, updated 2 packages and audited 245 packages in 1.528s

46 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

$ npx textlint sample.tex
$ echo $?
0
```

### PR DESCRIPTION
**Pull request by pddg**
fix  #140

### CODE REVIEW

**Review by kn1cht — APPROVED** [review]

**Comment by pddg** [comment]
@kn1cht 
eslint shows an error since the files in `test` directory are excluded from the project defined by tsconfig. 
Do you have any solution?

**Comment by kn1cht** [comment]
@pddg I added "test/" to .eslintignore and the errors disappeard

**Comment by pddg** [comment]
@kn1cht 
I don't really want to choose that option, because I still want to run lint......

**Comment by kn1cht** [comment]
reading this : https://github.com/typescript-eslint/typescript-eslint/issues/1350

**Comment by pddg** [comment]
OK. I added `tsconfig.eslint.json` and include test files in that project.

**Review by kn1cht — APPROVED** [review]

**Comment by kn1cht** [comment]
LGTM, nice work!

**Pull request merged**
